### ISSUE TITLE
session not being recorded when integrating through segment

### ISSUE THREAD

**Issue by kilianc** [segment-integrations/analytics.js-integration-inspectlet#1]
I don't get any error and the `__insp` appears to be set, but the sessions don't show up in the dashbord. I double checked all settings and the page event is coming in correctly, and all other integrations are working.

Any hint ? Hopefully this is not a bug and I am missing something.

**Comment by f2prateek** [comment]
Can you email friends@segment.com? Just so it gets in front of our support team who can take a deeper look.

**Comment by kilianc** [comment]
thanks

**Comment by kilianc** [comment]
After speaking with support it turned out I integrated everything correctly but despite the fact that the documentation does not mention it, you need to fire a track event to start a session (?)

I don't understand the reasoning behind this choice considering that this is not the behavior of Inspectlet when installed through it's own snippet.

* Why a session is not worth recording if the user only scrolls the page it's not clear. Passive sessions are the one I need to fix, I need to see them more than anything.
* I would be ok if there was an API to start the session manually, I am always down to have more control. But it smells that the API is indeed `track()` which will be sent to all my other integrations. What exactly am I tracking?

**Comment by f2prateek** [comment]
You can track a session started event - `analytics.track("session started")`.

**Comment by kilianc** [comment]
@f2prateek do you feel like this is how is supposed to work?

**Comment by f2prateek** [comment]
I am not too familiar with inspectlet and this integration, but if they need an explicit signal to start recording a session (which sounds like they do), then a track event is the best way to do it. We don't support every partner API directly (i.e. in this case, we don't have a start/stop session method) to keep our API simple.

**Comment by f2prateek** [comment]
(Either way, this is probably something we note in the docs)

**Comment by kilianc** [comment]
@f2prateek when I use their own snippet it doesn't need any manual event triggering. I completely understand you guys won't clutter the `analytics.js` API with third party methods, I am just trying to understand why it doesn't work :D

**Comment by f2prateek** [comment]
How are you loading their script? We just add a script tag to the page - https://github.com/segment-integrations/analytics.js-integration-inspectlet/blob/master/lib/index.js#L18. Maybe the initialization code is different from what you had in a native integration? https://github.com/segment-integrations/analytics.js-integration-inspectlet/blob/master/lib/index.js#L29-L30

If we're doing the same as you are, then I'm surprised it doesn't just work out of the box.

**Comment by kilianc** [comment]
> I'm surprised it doesn't just work out of the box.

Now we're talking.

Maybe they hook up to `'load'` event which is already fired when segment attaches the script? I can provide a test environment URL to debug this further.

**Comment by f2prateek** [comment]
Looking at their snippet, they do the same we do https://www.inspectlet.com/docs, i.e. simply drop a script tag on the page.

```js
<!-- Begin Inspectlet Embed Code -->
< script type = "text/javascript"
id = "inspectletjs" >
    window.__insp = window.__insp || [];
__insp.push(['wid', 12345678]);
(function() {
    function ldinsp() {
        if (typeof window.__inspld != "undefined") return;
        window.__inspld = 1;
        var insp = document.createElement('script');
        insp.type = 'text/javascript';
        insp.async = true;
        insp.id = "inspsync";
        insp.src = ('https:' == document.location.protocol ? 'https' : 'http') + '://cdn.inspectlet.com/inspectlet.js';
        var x = document.getElementsByTagName('script')[0];
        x.parentNode.insertBefore(insp, x);
    };
    setTimeout(ldinsp, 500);
    document.readyState != "complete" ? (window.attachEvent ? window.attachEvent('onload', ldinsp) : window.addEventListener('load', ldinsp, false)) : ldinsp();
})(); < /script>
<!-- End Inspectlet Embed Code -->
```

**Comment by f2prateek** [comment]
@kilianc Might be worth looping in any inspect let people into this thread, I've asked for contacts from our partners team, but feel free to ping any of your contacts as well.

**Comment by kilianc** [comment]
That's what I thought, it should auto start right? I don't understand why `.track()` has a role in all this.

**Comment by kilianc** [comment]
I activated the integration in live mode and I'll leave it there for a day. I'll be back with some data.

**Comment by inspectlet** [comment]
Hmm that's odd, I just installed Inspectlet via Segment on a boilerplate page and it starts tracking without needing to fire a track event. @kilianc what's the live URL for the site? I'd love to take a look!

**Comment by kilianc** [comment]
https://lukibear.com I really hope it was just a momentary issue or my mistake somewhere :)

**Comment by inspectlet** [comment]
I just visited the home page and it recorded the visit successfully at https://www.inspectlet.com/dashboard/captures/2147080968 , are you logged into a different account than info@lukibear.com by any chance? There are another ~50 recordings in here from today :)

**Comment by kilianc** [comment]
@inspectlet I know, I had it installed manually until few minutes agò and just switched since everyone was trying to help me out :)

I'll close this and reopen in case it doesn't work again!
